### ISSUE TITLE
你好老哥，那个下载电报群组频道文件的问题

### ISSUE THREAD

**Issue by ajaxadmin** [Mpk2022/-#1]
找到可用的方案了吗，可以给提供个思路吗，我看你用的rclone自动同步的。可以下载历史文件吗

**Comment by Mpk2022** [comment]
我试过这个(https://github.com/Dineshkarthik/telegram_media_downloader)只能下载，不能上传。
解决办法是：使用screen -S tg新建一个窗口，然后执行  while true ;do rclone move -v 文件路径 rclone名字:/ --transfers=1 ; sleep 200;done;2     循环执行（200s执行一次）然后按ctrl a d 关闭ssh 就能vps后台挂着了。
最近没怎么用过，忙着写论文。

**Comment by ajaxadmin** [comment]
好的，谢谢，那个国人写的那个已经改好了，可以正常用了，我再魔改下加点上传功能。

**Comment by ajaxadmin** [comment]
![)3JYI@0MQ8((VYJSTEB0@XE](https://user-images.githubusercontent.com/87073825/159156615-d2c18ddf-b596-46ce-918c-9060a9db5e9f.png)
![B`7UY J$ABIVQ6M63 KFYQX](https://user-images.githubusercontent.com/87073825/159156617-bca1c025-b765-47ff-a4ee-d1cad35f6212.png)
打扰了老哥，那个项目搞不定又回到你说的这个了，搞了半天了发现脚本跑起来没动静，你看下配置是这样配置的吗。有偿解决问题

**Comment by Mpk2022** [comment]
打马赛克，小心泄露

**Comment by Mpk2022** [comment]
我刚在vps上试了一下，可以跑起来
![image](https://user-images.githubusercontent.com/97872318/159206579-00dd1610-7064-4fae-b059-dfa24e838c63.png)
我感觉可能是你的chat_id填的不对
![image](https://user-images.githubusercontent.com/97872318/159206852-e99beab6-0467-4d5a-9559-4075d30343cf.png)

**Comment by ajaxadmin** [comment]
好的，感谢
